server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3366/elaparato?serverTimezone=UTC&useSSL=false
    username: user
    password: pwd-user
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
